# -*- coding: utf-8 -*-
"""Trainingwith2019.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AmZ5W8upFvv29_UCsi0qiC4grJKv-AZL
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#loading data
dataset = pd.read_excel('Data.xlsx')
x=dataset.iloc[:,1:-1].values
y=dataset.iloc[:,-1].values

x=pd.DataFrame(x)
y=pd.DataFrame(y)

import re
#checking notout
def match(df):
  if re.match(r"[0-9]+[*]$",df):
    return True
  else:
    return False

x[4]=x[4].apply(str)
x[12]=12

import re
for i in range(len(x[4])):
  if match(x[4][i]):
    x[12][i]=1
    x[4][i]=re.sub(r"[*]","",x[4][i])
  else:
    x[12][i]=0
  if x[5][i]=='-':
    x[5][i]=x[3][i]

#dropping columns
x.drop([0,1,2,6,7,8,9,12],axis=1, inplace=True)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y,test_size=0.20,random_state=0)

from sklearn.ensemble import RandomForestRegressor
regressor= RandomForestRegressor( n_estimators=100, random_state=0)
regressor.fit(x_train,y_train)
y_pred=regressor.predict(x_test)

print(y_pred)

from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

